var annotated_dup =
[
    [ "msceqf", null, [
      [ "BiasState", "structmsceqf_1_1_bias_state.html", "structmsceqf_1_1_bias_state" ],
      [ "Camera", "structmsceqf_1_1_camera.html", "structmsceqf_1_1_camera" ],
      [ "CameraExtrinsicState", "structmsceqf_1_1_camera_extrinsic_state.html", "structmsceqf_1_1_camera_extrinsic_state" ],
      [ "CameraIntrinsicState", "structmsceqf_1_1_camera_intrinsic_state.html", "structmsceqf_1_1_camera_intrinsic_state" ],
      [ "CameraOptions", "structmsceqf_1_1_camera_options.html", "structmsceqf_1_1_camera_options" ],
      [ "Checker", "classmsceqf_1_1_checker.html", "classmsceqf_1_1_checker" ],
      [ "CheckerOptions", "structmsceqf_1_1_checker_options.html", "structmsceqf_1_1_checker_options" ],
      [ "EquidistantCamera", "structmsceqf_1_1_equidistant_camera.html", "structmsceqf_1_1_equidistant_camera" ],
      [ "ExtendedPoseState", "structmsceqf_1_1_extended_pose_state.html", "structmsceqf_1_1_extended_pose_state" ],
      [ "FastOptions", "structmsceqf_1_1_fast_options.html", "structmsceqf_1_1_fast_options" ],
      [ "FeatHelper", "structmsceqf_1_1_feat_helper.html", "structmsceqf_1_1_feat_helper" ],
      [ "Features", "structmsceqf_1_1_features.html", "structmsceqf_1_1_features" ],
      [ "FeatureState", "structmsceqf_1_1_feature_state.html", "structmsceqf_1_1_feature_state" ],
      [ "GFTTOptions", "structmsceqf_1_1_g_f_t_t_options.html", "structmsceqf_1_1_g_f_t_t_options" ],
      [ "Imu", "structmsceqf_1_1_imu.html", "structmsceqf_1_1_imu" ],
      [ "InitializerOptions", "structmsceqf_1_1_initializer_options.html", "structmsceqf_1_1_initializer_options" ],
      [ "MSCEqF", "classmsceqf_1_1_m_s_c_eq_f.html", "classmsceqf_1_1_m_s_c_eq_f" ],
      [ "MSCEqFInState", "structmsceqf_1_1_m_s_c_eq_f_in_state.html", "structmsceqf_1_1_m_s_c_eq_f_in_state" ],
      [ "MSCEqFOptions", "structmsceqf_1_1_m_s_c_eq_f_options.html", "structmsceqf_1_1_m_s_c_eq_f_options" ],
      [ "MSCEqFSDBState", "structmsceqf_1_1_m_s_c_eq_f_s_d_b_state.html", "structmsceqf_1_1_m_s_c_eq_f_s_d_b_state" ],
      [ "MSCEqFSE3State", "structmsceqf_1_1_m_s_c_eq_f_s_e3_state.html", "structmsceqf_1_1_m_s_c_eq_f_s_e3_state" ],
      [ "MSCEqFSOT3State", "structmsceqf_1_1_m_s_c_eq_f_s_o_t3_state.html", "structmsceqf_1_1_m_s_c_eq_f_s_o_t3_state" ],
      [ "MSCEqFState", "classmsceqf_1_1_m_s_c_eq_f_state.html", "classmsceqf_1_1_m_s_c_eq_f_state" ],
      [ "MSCEqFStateElement", "classmsceqf_1_1_m_s_c_eq_f_state_element.html", "classmsceqf_1_1_m_s_c_eq_f_state_element" ],
      [ "OptionParser", "classmsceqf_1_1_option_parser.html", "classmsceqf_1_1_option_parser" ],
      [ "PinholeCamera", "classmsceqf_1_1_pinhole_camera.html", "classmsceqf_1_1_pinhole_camera" ],
      [ "ProjectionHelper", "classmsceqf_1_1_projection_helper.html", "classmsceqf_1_1_projection_helper" ],
      [ "ProjectionHelperS2", "classmsceqf_1_1_projection_helper_s2.html", "classmsceqf_1_1_projection_helper_s2" ],
      [ "ProjectionHelperZ1", "classmsceqf_1_1_projection_helper_z1.html", "classmsceqf_1_1_projection_helper_z1" ],
      [ "Propagator", "classmsceqf_1_1_propagator.html", "classmsceqf_1_1_propagator" ],
      [ "PropagatorOptions", "structmsceqf_1_1_propagator_options.html", "structmsceqf_1_1_propagator_options" ],
      [ "RadtanCamera", "structmsceqf_1_1_radtan_camera.html", "structmsceqf_1_1_radtan_camera" ],
      [ "StateOptions", "structmsceqf_1_1_state_options.html", "structmsceqf_1_1_state_options" ],
      [ "StaticInitializer", "classmsceqf_1_1_static_initializer.html", "classmsceqf_1_1_static_initializer" ],
      [ "Symmetry", "classmsceqf_1_1_symmetry.html", null ],
      [ "SystemState", "classmsceqf_1_1_system_state.html", "classmsceqf_1_1_system_state" ],
      [ "SystemStateElement", "classmsceqf_1_1_system_state_element.html", "classmsceqf_1_1_system_state_element" ],
      [ "Track", "structmsceqf_1_1_track.html", "structmsceqf_1_1_track" ],
      [ "Tracker", "classmsceqf_1_1_tracker.html", "classmsceqf_1_1_tracker" ],
      [ "TrackerOptions", "structmsceqf_1_1_tracker_options.html", "structmsceqf_1_1_tracker_options" ],
      [ "TrackManager", "classmsceqf_1_1_track_manager.html", "classmsceqf_1_1_track_manager" ],
      [ "TrackManagerOptions", "structmsceqf_1_1_track_manager_options.html", "structmsceqf_1_1_track_manager_options" ],
      [ "TriangulatedFeatures", "structmsceqf_1_1_triangulated_features.html", "structmsceqf_1_1_triangulated_features" ],
      [ "Updater", "classmsceqf_1_1_updater.html", "classmsceqf_1_1_updater" ],
      [ "UpdaterHelper", "structmsceqf_1_1_updater_helper.html", null ],
      [ "UpdaterOptions", "structmsceqf_1_1_updater_options.html", "structmsceqf_1_1_updater_options" ],
      [ "Visualizer", "classmsceqf_1_1_visualizer.html", "classmsceqf_1_1_visualizer" ],
      [ "ZeroVelocityUpdater", "classmsceqf_1_1_zero_velocity_updater.html", "classmsceqf_1_1_zero_velocity_updater" ],
      [ "ZeroVelocityUpdaterOptions", "structmsceqf_1_1_zero_velocity_updater_options.html", "structmsceqf_1_1_zero_velocity_updater_options" ]
    ] ],
    [ "utils", null, [
      [ "InsertionOrderedMap", "classutils_1_1_insertion_ordered_map.html", "classutils_1_1_insertion_ordered_map" ],
      [ "is_streamable", "structutils_1_1is__streamable.html", null ],
      [ "is_streamable< S, C, decltype(void(std::declval< S & >()<< std::declval< C const & >()))>", "structutils_1_1is__streamable_3_01_s_00_01_c_00_01decltype_07void_07std_1_1declval_3_01_s_01_6_0f58e90958705880955bd917882569c69.html", null ],
      [ "Logger", "classutils_1_1_logger.html", null ]
    ] ],
    [ "MSCEqFRos", "class_m_s_c_eq_f_ros.html", "class_m_s_c_eq_f_ros" ]
];