FROM osrf/ros:noetic-desktop-full

RUN apt-get update && apt-get install -y nano git
RUN sudo apt-get install -y python3-catkin-tools python3-osrf-pycommon python3-wstool build-essential

RUN mkdir -p /root/catkin_ws/src/msceqf
COPY . /root/catkin_ws/src/msceqf/

RUN apt update
RUN echo 'source /root/catkin_ws/devel/setup.bash' >> /root/.bashrc
RUN /bin/bash -c "source /root/.bashrc"

WORKDIR /root